from sqlalchemy import Column, Integer, String, Text, DateTime, func
from app.core.database import Base


class Artist(Base):
    __tablename__ = "artists"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, nullable=False, unique=True, comment="姓名")
    alias = Column(String, default="", comment="字号")
    dynasty = Column(String, default="", comment="朝代")
    hometown = Column(String, default="", comment="籍贯")
    birth_year = Column(Integer, nullable=True, comment="出生年份")
    death_year = Column(Integer, nullable=True, comment="卒年")
    avatar_url = Column(String, default="", comment="头像URL")
    biography = Column(Text, default="", comment="生平简介")
    background = Column(String, default="", comment="背景简介（旧）")
    specialties = Column(String, default="", comment="专长（旧）")
    bio_events = Column(Text, default="[]", comment="生平时间线 JSON")
    art_school = Column(String, default="", comment="画派（逗号分隔）")
    masterpieces = Column(Text, default="[]", comment="代表作 JSON 数组")
    tags = Column(Text, default="[]", comment="标签 JSON 数组")
    baidu_url = Column(String, default="", comment="百度百科 URL")
    view_count = Column(Integer, default=0, comment="浏览量")
    featured = Column(Integer, default=0, comment="推荐标记 1推荐/0非推荐")
    enabled = Column(Integer, default=1, comment="启用状态")
    verified = Column(Integer, default=0, comment="认证标记 1已认证/0未认证")
    banner_url = Column(String, default="", comment="封面题图URL")
    summary = Column(Text, default="", comment="概述文字")
    nationality = Column(String, default="", comment="国籍")
    occupation = Column(String, default="", comment="职业")
    main_achievements = Column(Text, default="", comment="主要成就")
    representative_works_text = Column(String, default="", comment="代表作品文本")
    art_style = Column(Text, default="", comment="艺术特色")
    influence = Column(Text, default="", comment="后世影响")
    historical_evaluation = Column(Text, default="", comment="历史评价")
    character_relations = Column(Text, default="[]", comment="人物关系 JSON")
    anecdotes = Column(Text, default="[]", comment="轶事典故 JSON")
    art_chronology = Column(Text, default="[]", comment="艺术年谱 JSON")
    published_works = Column(Text, default="[]", comment="出版著作 JSON")
    gallery_images = Column(Text, default="[]", comment="作品图集 JSON")
    photos = Column(Text, default="[]", comment="本人照片 JSON 数组")
    references = Column(Text, default="[]", comment="参考文献 JSON")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
