server {
    listen 80;
    server_name zhouhouhan.com;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name zhouhouhan.com;

    ssl_certificate     /etc/letsencrypt/live/zhouhouhan.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/zhouhouhan.com/privkey.pem;

    client_max_body_size 30M;

    location / {
        proxy_pass http://backend:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 180s;
    }
}
